include: package:flutter_lints/flutter.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - content_suppliers_api/*
    - content_suppliers_rust/*
    - "**/*.g.dart"
linter: 
  rules:
    implicit_call_tearoffs: false
