include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
    - content_suppliers_api/*
    - content_suppliers_rust/*
    - "**/*.g.dart"
    - "**/*.freezed.dart"