name: Build Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-for-android:
    permissions: write-all
    uses: ./.github/workflows/build-android.yaml
    secrets: inherit

  build-for-linux:
    permissions: write-all
    uses: ./.github/workflows/build-linux.yaml
    secrets: inherit

  build-for-windows:
    permissions: write-all
    uses: ./.github/workflows/build-windows.yaml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    name: "Create Release"
    permissions: write-all
    needs: [build-for-android, build-for-linux, build-for-windows]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CHANGELOG.md
          sparse-checkout-cone-mode: false
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-outputs
          path: android-outputs
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-outputs
          path: linux-outputs
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-outputs
          path: windows-outputs
      - name: RePackage Desktops
        run: |
          chmod +x linux-outputs/strumok
          tar -czf strumok-linux.tar.gz -C linux-outputs .
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body_path: CHANGELOG.md
          files: |
            android-outputs/*
            strumok-linux.tar.gz
            strumok-windows.zip
            windows-outputs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}