name: Release

on:
  workflow_dispatch:

jobs:
  bump-release: 
    runs-on: ubuntu-latest
    name: "Bump Release"
    permissions: write-all
    outputs:
      tag: ${{ steps.changelog.outputs.tag  }}
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
    
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v5
      with:
        github-token: ${{ github.token }}
        version-file: "pubspec.yaml"
        release-count: 1

  build-for-android:
    needs: [bump-release]
    permissions: write-all
    uses: ./.github/workflows/build-android.yaml
    secrets: inherit

  build-for-linux:
    needs: [bump-release]
    permissions: write-all
    uses: ./.github/workflows/build-linux.yaml
    secrets: inherit

  build-for-windows:
    needs: [bump-release]
    permissions: write-all
    uses: ./.github/workflows/build-windows.yaml
    secrets: inherit

  create-release:
    permissions: write-all
    needs: [build-for-android, build-for-linux, build-for-windows, bump-release]
    uses: ./.github/workflows/upload-release.yaml
    secrets: inherit
    with:
      tag_name: ${{ needs.bump-release.outputs.tag }}
