name: Release

on:
  workflow_dispatch:

jobs:
  bump-release: 
    runs-on: ubuntu-latest
    name: "Bump Release"
    permissions: write-all
    outputs:
      tag: ${{ steps.changelog.outputs.tag  }}
      body: ${{ steps.changelog.outputs.clean_changelog }}
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
    
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version-file: "pubspec.yaml"
        release-count: 1