name: Upload Release

on:
  workflow_call:
    inputs:
      tag_name:
        description: "Release Name"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    name: "Create Release"
    permissions: write-all
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          tag_name: ${{ inputs.tag_name }}
          sparse-checkout: |
            CHANGELOG.md
          sparse-checkout-cone-mode: false
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-outputs
          path: android-outputs
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-outputs
          path: linux-outputs
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-outputs
          path: windows-outputs
      - name: RePackage Desktops
        run: |
          chmod +x linux-outputs/strumok
          tar -czf strumok-linux.tar.gz -C linux-outputs .
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: ${{ inputs.tag_name }}
          tag_name: ${{ inputs.tag_name }}
          body: CHANGELOG.md
          files: |
            android-outputs/*
            strumok-linux.tar.gz
            strumok-windows.zip
            windows-outputs/*